const express=require("express")
const app=express()
const path=require("path")
const bodyParser=require("body-parser")
const userRouter=require("./userRoutes/user.route")
const blogRouter=require("./blogsRoutes/blogs.routes")
app.set("view engine","ejs")
// app.set("views","views")
app.use(express.static(path.join(__dirname,'public')))
app.use(bodyParser.urlencoded({extended:true}))
app.use(express.json())
// app.use(blogRouter)
app.use(userRouter)
app.listen(3000,()=>{
  console.log("server is up on port 3000")
})
